# uS10_iqtree.sub
# Submission file for IQ-TREE phylogeny reconstruction for SSU job
#
# Specify the HTCondor Universe (vanilla is the default and is used
#  for almost all jobs) and your desired name of the HTCondor log file,
#  which is where HTCondor will describe what steps it takes to run 
#  your job. Wherever you see $(Cluster), HTCondor will insert the 
#  queue number assigned to this set of jobs at the time of submission.
universe = vanilla
log = $(SUBMIT_FILE)_$(Cluster).log
#
# Specify your executable (single binary or a script that runs several
#  commands), arguments, and a files for HTCondor to store standard
#  output (or "screen output").
#  $(Process) will be a integer number for each job, starting with "0"
#  and increasing for the relevant number of jobs.
executable = uS10_iqtree.sh
# arguments = 
output = $(SUBMIT_FILE)_$(Cluster).out
error = $(SUBMIT_FILE)_$(Cluster).err
#
# Specify that HTCondor should transfer files to and from the
#  computer where each job runs. The last of these lines should be
#  used if there are any other files needed for the executable to use.
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = uS10_common_mafft.fasta, /home/fer/iqtree
#
# Tell HTCondor what amount of compute resources
#  each job will need on the computer where it runs.
request_cpus = 12
request_memory = 50GB
request_disk = 50GB
#
# Run one instance of job
queue
